### PR TITLE
Fixed obscure/wrong installation section.

### PR DESCRIPTION
**Pull request by smrsan76**

### CODE REVIEW

**Comment by andersevenrud** [comment]
Hm. Actually,  `@osjs/cli` is a dependency in `OS.js`.

The `npm run package:discover` command runs `npx osjs-cli package:discover` (just an alias), where `npx` is a builtin `npm` binary that runs any script in `node_modules/.bin`.

So the current method is the correct one.

I'm interested to know why this is obscure or wrong though. Did you get some errors or something ? :)

**Comment by smrsan76** [comment]
Excuse me if I said "wrong" for this issue ...
but my problem is that I can't use `npm run package:discover` in my osjs directory !

it errors like this:
```
npm ERR! missing script: package:discover
```

**Comment by andersevenrud** [comment]
What's the contents of your `package.json` file in the directory you're running the discovery command ?

**Comment by andersevenrud** [comment]
As discussed in Gitter, this was simply a trifle relating to checking out wrong repo. Closing :)

**Comment by andersevenrud** [comment]
I've also added the same "deprecation notice" on the INSTALL.md file in the master branch as in README.md file.

**Pull request closed without merging**
